/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfredo
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Cargar_Porcentajes();
    }
    
    public void Cargar_Porcentajes(){
         ArrayList<Integer> guia = new ArrayList<>();
         guia.add(40); guia.add(20);
         
         ArrayList<Integer> lectura = new ArrayList<>();
         lectura.add(20); lectura.add(0);
         
         for( Integer item : guia ){
             cb_Guia.addItem(item+"%");
         }
         
         for ( Integer item : lectura){
             cb_Control_Lectura.addItem(item+"%");
         }
         
         cb_Control_Lectura.setSelectedItem("0%");
    }
    
    public boolean ValidarControles(){
        
        if (txt_Nombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar nombre del estudiante");
            return false;
        }
        
        if (txt_Parcial.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar nota del parcial");
            return false;
        }
        
        if (txt_Guia.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar nota de la guía");
            return false;
        }
        
        if (txt_Control_Lectura.isEnabled() && txt_Control_Lectura.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingresar nota del control de lectura");
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Parcial = new javax.swing.JTextField();
        txt_Guia = new javax.swing.JTextField();
        txt_Control_Lectura = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lb_Porcentaje = new javax.swing.JLabel();
        cb_Control_Lectura = new javax.swing.JComboBox<>();
        cb_Guia = new javax.swing.JComboBox<>();
        btn_Calcular = new javax.swing.JButton();
        btn_Contacto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE DEL ALUMNO");

        jLabel2.setText("PARCIAL");

        jLabel3.setText("GUÍA");

        jLabel4.setText("CONTROL DE LECTURA");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("PORCENTAJE");

        lb_Porcentaje.setText("60%");

        cb_Guia.addItemListener(this::cb_GuiaItemStateChanged);

        btn_Calcular.setText("CALCULAR PROMEDIO");
        btn_Calcular.addActionListener(this::btn_CalcularActionPerformed);

        btn_Contacto.setText("CONTACTO");
        btn_Contacto.addActionListener(this::btn_ContactoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txt_Nombre)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Parcial, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(txt_Guia)
                            .addComponent(txt_Control_Lectura))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lb_Porcentaje)
                    .addComponent(cb_Control_Lectura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Guia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Contacto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_Parcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txt_Guia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Control_Lectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28)
                                .addComponent(lb_Porcentaje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_Guia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cb_Control_Lectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Calcular)
                    .addComponent(btn_Contacto))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_GuiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_GuiaItemStateChanged
        // TODO add your handling code here:
        
        if (evt.getStateChange() == ItemEvent.SELECTED){
            String opcion = cb_Guia.getSelectedItem().toString();
                    if ("40%".equals(opcion)){
                    txt_Control_Lectura.setText("");
                    txt_Control_Lectura.setEnabled(false);
                    cb_Control_Lectura.setEnabled(false);
                    cb_Control_Lectura.setSelectedItem("0%");
                    }
                    else{
                        txt_Control_Lectura.setEnabled(true);
                        cb_Control_Lectura.setEnabled(true);
                        cb_Control_Lectura.setSelectedItem("20%");
                    }
       }
    }//GEN-LAST:event_cb_GuiaItemStateChanged

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        // TODO add your handling code here:
        
        if (ValidarControles()){
            String estudiante = "";
            double parcial = 0.0;
            double guia = 0.0;
            double lectura = 0.0;
            Integer porcentaje_guia = 0;
            Integer porcentaje_lectura = 0;
            
            estudiante = txt_Nombre.getText();
            
            try{
                parcial = Double.parseDouble(txt_Parcial.getText());
                guia = Double.parseDouble(txt_Guia.getText());

                if (txt_Control_Lectura.isEnabled()){
                    lectura = Double.parseDouble(txt_Control_Lectura.getText());
                    porcentaje_lectura = Integer.parseInt(cb_Control_Lectura.getSelectedItem().toString().replace("%", ""));
                }                
                
                porcentaje_guia = Integer.parseInt(cb_Guia.getSelectedItem().toString().replace("%", ""));
                
                double r_parcial = parcial * 0.60;
                double r_guia = guia * porcentaje_guia/100;
                double r_lectura = lectura * porcentaje_lectura/100;
                
                double promedio = r_parcial + r_guia + r_lectura;
                                
                JOptionPane.showMessageDialog(null, "Promedio: "+promedio+"\n"+estudiante);
            }catch(Exception ex) {
                JOptionPane.showMessageDialog(null, "Error en los campos de notas");
            }
        }
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void btn_ContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ContactoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Alfredo Antonio Navarro Guido\n29-1149-2014");
    }//GEN-LAST:event_btn_ContactoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Contacto;
    private javax.swing.JComboBox<String> cb_Control_Lectura;
    private javax.swing.JComboBox<String> cb_Guia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lb_Porcentaje;
    private javax.swing.JTextField txt_Control_Lectura;
    private javax.swing.JTextField txt_Guia;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Parcial;
    // End of variables declaration//GEN-END:variables
}
